### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Kasulejoseph**
This PR add index.html, style.css and modify the readme file

### CODE REVIEW

**Comment by barema4** [comment]
I think you should include pivotal tracker id on every commit you make

**Comment by mozzy11** [comment]
hello @Kasulejoseph , am wondering y u have merge conflicts, u probably had to create the develop off master, u wudnt have had merge conflicys

**Comment by HarunaIbnYusuf** [comment]
It looks OK but how can i use link to your pivotal story

**Comment by HKiwooma** [comment]
It looks OK but how try attach a link to your pivotal story

**Pull request merged**
